default_platform(:ios)

platform :ios do
  desc "Upload metadata to App Store Connect"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      metadata_path: "./fastlane/metadata/ios",
      screenshots_path: "./fastlane/screenshots/ios",
      force: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Upload screenshots only"
  lane :screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata: true,
      screenshots_path: "./fastlane/screenshots/ios",
      force: true
    )
  end
end

platform :android do
  desc "Upload metadata to Google Play"
  lane :metadata do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: false,
      metadata_path: "./fastlane/metadata/android"
    )
  end

  desc "Upload screenshots only"
  lane :screenshots do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      skip_upload_images: false,
      metadata_path: "./fastlane/metadata/android"
    )
  end
end
