import { db } from './index.js';
import { achievements, scenarios } from './schema.js';
import { sql } from 'drizzle-orm';

const ACHIEVEMENTS_DATA = [
  { id: 'first_vote', name: 'First Verdict', description: 'Cast your first verdict', icon: '⚖️', xpReward: 20 },
  { id: 'streak_7', name: 'Weekly Judge', description: '7-day voting streak', icon: '🔥', xpReward: 50 },
  { id: 'streak_30', name: 'Monthly Verdict', description: '30-day voting streak', icon: '💪', xpReward: 100 },
  { id: 'streak_365', name: 'Incorruptible Judge', description: '365-day voting streak', icon: '👑', xpReward: 500 },
  { id: 'contrarian_10', name: 'Rebel', description: 'Vote against the majority 10 times', icon: '🏴‍☠️', xpReward: 50 },
  { id: 'consensus_10', name: 'Voice of the People', description: 'Vote with 70%+ majority 10 times', icon: '🗳️', xpReward: 50 },
  { id: 'league_diamond', name: 'Diamond League', description: 'Reach Diamond tier', icon: '💎', xpReward: 100 },
  { id: 'league_amethyst', name: 'Legendary Judge', description: 'Reach Amethyst tier', icon: '🟣', xpReward: 200 },
  { id: 'submit_approved', name: 'Story Author', description: 'Get your scenario approved', icon: '✍️', xpReward: 75 },
  { id: 'challenge_win_5', name: 'Challenger', description: 'Complete 5 friend challenges', icon: '⚔️', xpReward: 50 },
];

// 95 scenarios for launch — morally ambiguous, realistic, first-person
const SCENARIOS_DATA: Array<{ title: string; body: string; category: string }> = [
  // WORKPLACE (16)
  { title: "I reported my coworker's mistake to the boss", body: "My coworker made a serious error on a client report that could have cost us the account. Instead of telling her first, I went straight to our manager. She found out and says I stabbed her in the back. I say I was protecting the team and the client. She's barely speaking to me now.", category: 'workplace' },
  { title: "I refused to cover for a sick colleague", body: "My colleague called in sick on the day of a big presentation. My boss asked me to step in. I said no because I had my own deadlines and wasn't prepared for her material. The presentation got postponed and the client was annoyed. My boss says I should have been a team player.", category: 'workplace' },
  { title: "I took credit for a team idea", body: "During a brainstorm, my team came up with a concept together. When the VP asked who came up with it in a meeting, I said it was my idea. I did contribute the core concept, but others refined it. Now my teammates are furious and say I stole their work.", category: 'workplace' },
  { title: "I refused to train my replacement", body: "After giving my two weeks notice, my boss asked me to train the person replacing me. I refused because they had consistently underpaid me for years and denied my raise requests. HR says I'm burning bridges, but I feel I don't owe them anything beyond my notice period.", category: 'workplace' },
  { title: "I secretly applied for my manager's job", body: "My manager announced she's going on maternity leave. Without telling her, I applied for her position as a permanent replacement. She found out and accused me of trying to steal her job while she's vulnerable. I say it's just career advancement.", category: 'workplace' },
  { title: "I reported a coworker for time theft", body: "I noticed my coworker leaves 30 minutes early every day but logs full hours. I reported it to HR anonymously. She got written up, figured out it was me, and now the whole team thinks I'm a snitch. I just wanted fairness since I work my full hours.", category: 'workplace' },
  { title: "I refused to share my commission", body: "A colleague helped me with a client pitch but I closed the deal myself. She wants half my commission. I offered 20% since I did all the follow-up work and client management. She says without her research, I'd have nothing. My manager won't intervene.", category: 'workplace' },
  { title: "I told an intern the truth about our company", body: "An excited new intern asked me about growth opportunities. I honestly told her that promotions are rare, the pay is below market, and most people leave within two years. My boss found out and said I'm poisoning new hires. I think honesty is better than false promises.", category: 'workplace' },
  { title: "I turned down overtime during a crisis", body: "Our company had a major system outage. My boss asked everyone to work the weekend. I declined because it was my daughter's birthday. The team had to work harder without me. My boss says I showed where my priorities really are.", category: 'workplace' },
  { title: "I exposed my boss's fake resume", body: "I discovered my boss lied about having an MBA on her resume. I anonymously told HR. She got fired. Now my colleagues say I ruined someone's life over a piece of paper. I believe integrity matters, especially in leadership.", category: 'workplace' },
  { title: "I refused to mentor a junior colleague", body: "My company assigned me a junior developer to mentor. I told my manager I didn't have time because mentoring isn't in my job description and I'm not compensated for it. The junior dev feels rejected and my manager says I'm not a team player.", category: 'workplace' },
  { title: "I ate my coworker's clearly labeled lunch", body: "I was starving, had no money, and forgot my lunch. I ate my coworker's labeled meal from the fridge, planning to replace it. But she saw the empty container before I could buy a replacement. She's furious and reported me to HR.", category: 'workplace' },
  { title: "I refused to attend a mandatory team building", body: "My company organized a weekend team-building retreat. I refused to go because it's my personal time and I'm not being paid for it. My manager says it was mandatory and everyone else went. I'm now the only one who didn't attend.", category: 'workplace' },
  { title: "I negotiated a higher salary than my senior", body: "When I was hired, I negotiated aggressively and got a higher salary than people who've been here longer. A coworker found out through a payroll glitch and now the team resents me. I say I just negotiated well and it's the company's fault for underpaying them.", category: 'workplace' },
  { title: "I muted myself but forgot to stop screen sharing", body: "During a video meeting, I thought I was muted so I started texting my friend about how boring the presenter was. I was muted, but my screen was shared and everyone saw my messages. The presenter is devastated and I feel terrible.", category: 'workplace' },
  { title: "I refused to lie on a reference call", body: "A former colleague listed me as a reference. When the new company called, I was honest about her poor performance and frequent conflicts. She didn't get the job and found out I gave a negative reference. She says I sabotaged her career.", category: 'workplace' },

  // RELATIONSHIP (16)
  { title: "I checked my partner's phone", body: "My partner has been acting distant and secretive lately. While they were showering, I checked their phone and found flirty messages with a coworker. When I confronted them, they said nothing physical happened and that I violated their privacy by snooping.", category: 'relationship' },
  { title: "I gave my ex's dog away", body: "After we broke up, my ex left their dog with me 'temporarily' for 3 months. They kept postponing pickup. I found the dog a loving new home. My ex is devastated and says I had no right. I say they abandoned the dog.", category: 'relationship' },
  { title: "I told my partner's parents about the engagement", body: "My partner proposed but asked me to keep it secret for a month. I was so excited I told my parents, who told their parents. My partner is furious because they wanted to announce it in a special way. I couldn't contain my joy.", category: 'relationship' },
  { title: "I refused to delete my ex from social media", body: "My new partner asked me to unfriend my ex on all social media. I refused because we ended on good terms and share a friend group. My partner says keeping an ex on social media is disrespectful. I say it's controlling to demand that.", category: 'relationship' },
  { title: "I lied about my body count", body: "My partner asked about my past relationships. I significantly lowered the number because I was afraid of judgment. They found out the truth from a mutual friend and now feel like our whole relationship started with a lie.", category: 'relationship' },
  { title: "I planned a surprise party they explicitly said no to", body: "My partner told me they hate surprise parties. For their 30th, I threw one anyway because 'turning 30 is special.' They walked in, saw everyone, and left. They said I ignored their clearly stated boundary. I thought they'd change their mind.", category: 'relationship' },
  { title: "I told my partner they gained weight", body: "My partner asked if they looked good in a new outfit. I gently mentioned they'd gained some weight recently. They got upset and said I was body-shaming them. I thought I was being honest because they asked.", category: 'relationship' },
  { title: "I kept a major debt secret from my fiancé", body: "I have $40,000 in student loans that I never told my fiancé about. They found out when we applied for a mortgage. They say financial honesty is fundamental in a relationship. I was ashamed and planned to pay it off quietly.", category: 'relationship' },
  { title: "I invited my partner's estranged sibling", body: "My partner hasn't spoken to their brother in 5 years. I secretly invited him to our wedding because I believe family should reunite. My partner found out and is threatening to cancel the wedding. I was trying to heal their family.", category: 'relationship' },
  { title: "I refused to move for my partner's dream job", body: "My partner got their dream job offer in another city. I refused to move because I love my job, my friends are here, and my aging parents need me nearby. They took the job anyway and we're trying long-distance. They say I held them back.", category: 'relationship' },
  { title: "I read my partner's diary", body: "I found my partner's diary accidentally and read a few pages. I discovered they've been unhappy in our relationship for months but haven't said anything. When I brought it up, they were furious I read it. I'm hurt they couldn't talk to me.", category: 'relationship' },
  { title: "I gave away concert tickets my ex bought me", body: "Before our breakup, my partner bought expensive concert tickets for us. After the breakup, I took a friend instead. My ex says those were a gift for us and I should have offered them back. I say a gift is a gift.", category: 'relationship' },
  { title: "I told my friend her boyfriend is cheating", body: "I saw my best friend's boyfriend on a dating app. I showed her the screenshots. She confronted him, he denied it, and now she's angry at ME for 'stirring drama.' They're still together and she's not speaking to me.", category: 'relationship' },
  { title: "I refuse to say I love you first", body: "We've been dating for 8 months. My partner is waiting for me to say 'I love you' first. I do love them but I believe whoever feels it first should say it. They think I'm emotionally unavailable. I think it's a pointless power dynamic.", category: 'relationship' },
  { title: "I set up my friend on a date without telling her", body: "I told my single friend we were having a casual dinner. When she arrived, I'd also invited a guy I thought was perfect for her. She felt ambushed and embarrassed. I was just trying to help because she's been lonely.", category: 'relationship' },
  { title: "I proposed at someone else's wedding", body: "I proposed to my girlfriend at my best friend's wedding reception. Everyone cheered, but the bride was upset, saying I stole her spotlight. I thought it was romantic. My girlfriend said yes but now feels guilty.", category: 'relationship' },

  // FAMILY (16)
  { title: "I refused to lend money to my brother", body: "My brother asked me for $5,000 to cover his rent. I said no because he still owes me $2,000 from last time and spends money on expensive sneakers and eating out. He says family should always help family. I say he needs to learn financial responsibility.", category: 'family' },
  { title: "I didn't invite my dad's new wife to Thanksgiving", body: "My dad remarried 6 months after my mom's death. I didn't invite his new wife to our family Thanksgiving. Dad says I'm being disrespectful to his new relationship. I say it's too soon and mom's memory deserves respect.", category: 'family' },
  { title: "I told my niece Santa isn't real", body: "My 8-year-old niece asked me directly if Santa is real. I told her the truth. My sister is furious and says I ruined the magic of childhood. I believe kids deserve honesty when they ask direct questions.", category: 'family' },
  { title: "I refused to babysit my sister's kids again", body: "My sister asks me to babysit her three kids almost every weekend. I finally said no because I need my own time and she never offers to pay or reciprocate. She says I'm selfish and don't care about family. I'm just exhausted.", category: 'family' },
  { title: "I cut my parents off after they chose my sibling", body: "My parents gave my sister their house and left me nothing in their will despite us having equal relationships. When I confronted them, they said she needs it more because she has kids. I stopped talking to them entirely.", category: 'family' },
  { title: "I told my teenage son his art career is unrealistic", body: "My 17-year-old wants to skip college to pursue art. I told him he needs a real career first and can do art as a hobby. He says I'm crushing his dreams. I say I'm being realistic about financial survival.", category: 'family' },
  { title: "I went through my teenager's backpack", body: "I suspected my 15-year-old was vaping. I searched their backpack and found vape cartridges. When I confronted them, they said I violated their privacy. I say as a parent, their safety is my responsibility.", category: 'family' },
  { title: "I made my kids share a room for the guest room", body: "I made my two kids (10 and 12) share a bedroom so we could have a dedicated guest room for visiting family. They're upset about losing their space. I say hosting grandparents comfortably is important for everyone.", category: 'family' },
  { title: "I refused to co-sign my son's car loan", body: "My 22-year-old son asked me to co-sign a car loan. I refused because he has a history of irresponsible spending and I don't want to risk my credit. He says I don't believe in him. I say he needs to build credit on his own.", category: 'family' },
  { title: "I told my mother-in-law to stop visiting unannounced", body: "My mother-in-law has a key to our house and shows up whenever she wants. I changed the locks and told her to call before coming. My spouse says I disrespected their mother. I say boundaries are necessary for a healthy marriage.", category: 'family' },
  { title: "I chose my wedding over my sister's graduation", body: "My wedding and my sister's college graduation fell on the same day. I couldn't move the wedding due to venue and vendor commitments. She's devastated I won't be there for her big day. I feel terrible but the wedding was planned first.", category: 'family' },
  { title: "I stopped financially supporting my adult child", body: "My 26-year-old still lives with us and doesn't contribute to expenses. I gave them a 3-month deadline to get a job or move out. My spouse says I'm being harsh. I say I'm enabling them by not setting boundaries.", category: 'family' },
  { title: "I told my family about my sister's pregnancy", body: "My sister confided she was pregnant but told me not to tell anyone yet. I accidentally mentioned it to our mom. Mom told everyone. My sister hasn't spoken to me in two weeks. It genuinely slipped out.", category: 'family' },
  { title: "I made my daughter quit her sport", body: "My 14-year-old plays competitive soccer 6 days a week. Her grades dropped significantly. I made her quit until grades improve. She says soccer is her passion and I'm ruining her chances at a scholarship.", category: 'family' },
  { title: "I named my baby without consulting my partner", body: "While my partner was recovering from a difficult birth, I filled out the birth certificate with the name I preferred instead of the one we agreed on. They found out a week later. I loved this name more and thought they'd come around.", category: 'family' },
  { title: "I refused to attend my cousin's child-free wedding", body: "My cousin is having a child-free wedding. I have a toddler and no babysitter options. I told them I can't come. They're upset because we're close. I say the policy made it impossible for parents to attend.", category: 'family' },

  // NEIGHBORS (12)
  { title: "I called the city on my neighbor's tree", body: "My neighbor's tree drops leaves, branches, and fruit into my yard constantly. I asked them to trim it, they refused. I reported it to the city. Now they have to pay $800 for professional trimming and they're furious.", category: 'neighbors' },
  { title: "I confronted my neighbor about their barking dog", body: "My neighbor's dog barks from 6 AM to midnight. I asked them nicely three times to handle it. Nothing changed. I filed a noise complaint with the city. Now they leave angry notes on my car saying I'm trying to get their dog taken away.", category: 'neighbors' },
  { title: "I parked in my neighbor's 'spot'", body: "There's a public parking spot in front of my neighbor's house that they consider 'theirs.' I parked there because all other spots were taken. They left a furious note on my car. I say it's a public street and first come, first served.", category: 'neighbors' },
  { title: "I built a fence without asking", body: "I built a 6-foot privacy fence on my property line without consulting my neighbors. They're upset because it blocks their garden's sunlight. I checked local regulations and I'm within my rights. They say being legal doesn't make it right.", category: 'neighbors' },
  { title: "I reported my neighbor's Airbnb", body: "My neighbor turned their house into a party Airbnb. Every weekend, strangers are making noise until 3 AM. I reported it to the HOA and the city. The neighbor had to stop and lost significant income. They say I ruined their livelihood.", category: 'neighbors' },
  { title: "I put up security cameras pointing at the street", body: "After package thefts, I installed security cameras. My neighbor is uncomfortable because one camera captures their driveway. I adjusted the angle but they can still partially see their property. They say I'm surveilling them.", category: 'neighbors' },
  { title: "I let my kids play in the shared yard", body: "Our apartment complex has a shared green space. I let my kids (5 and 7) play there after school. A childless neighbor complained about the noise and toys. The landlord asked me to limit playtime. I say kids need outdoor space.", category: 'neighbors' },
  { title: "I complained about my neighbor's cooking smell", body: "My neighbor cooks with very strong spices that permeate the hallway and seep into my apartment. I asked the landlord to address it. My neighbor says I'm being culturally insensitive. I say I have the right to odor-free living.", category: 'neighbors' },
  { title: "I refused to chip in for a neighborhood party", body: "My neighbors organized a block party and asked every household to contribute $50. I declined because I wasn't consulted about the event and wouldn't attend. They say I'm antisocial and don't care about community. I say I shouldn't pay for events I didn't choose.", category: 'neighbors' },
  { title: "I cut my neighbor's vine growing on my fence", body: "My neighbor's vine has been growing over onto my fence and damaging it. I cut everything on my side without warning them. They're upset because it was a rare plant they've been nurturing for years. I say anything on my property is mine to manage.", category: 'neighbors' },
  { title: "I reported my neighbor for running a home business", body: "My neighbor runs a busy hair salon from their home. Cars block our street, clients ring my doorbell by mistake, and noise levels are high. I reported it to zoning. They face a $5,000 fine. They're a single mom just trying to make ends meet.", category: 'neighbors' },
  { title: "I refused to share my WiFi password", body: "My new neighbor asked if they could use my WiFi for a few days until their internet gets set up. I said no because of security concerns and bandwidth. It's been weeks and they still don't have internet. They think I'm selfish.", category: 'neighbors' },

  // FRIENDS (16)
  { title: "I uninvited my friend from the trip", body: "I planned a group trip and invited my friend. After booking, others said they wouldn't come if she did due to past drama. I uninvited her, citing 'logistics.' She found out the real reason. Says I chose others over our friendship.", category: 'friends' },
  { title: "I told my friend's secret at a party", body: "After a few drinks, I let slip that my friend was planning to quit her job. Word got back to her boss before she was ready. She got called in for a meeting and now she's devastated. I swear it was an accident.", category: 'friends' },
  { title: "I refused to be in my friend's wedding", body: "My friend asked me to be a bridesmaid, but being in the wedding would cost $3,000+ (dress, bachelorette trip, gifts). I declined because I can't afford it. She says I'm not prioritizing our friendship. I say real friends wouldn't bankrupt you.", category: 'friends' },
  { title: "I stopped inviting my always-late friend", body: "My friend is chronically 30-60 minutes late to everything. After years of waiting, I stopped inviting her to time-sensitive events. She found out others were meeting without her and is hurt. I say respecting others' time is basic courtesy.", category: 'friends' },
  { title: "I told my friend their startup idea is bad", body: "My friend excitedly shared their startup idea and asked for honest feedback. I told them it wouldn't work and listed specific reasons why. They were crushed and said I wasn't being supportive. I thought honesty was more helpful than false encouragement.", category: 'friends' },
  { title: "I won't lend my car to my best friend", body: "My best friend of 15 years asked to borrow my car for a weekend road trip. I said no because they've had two accidents in the past year. They say I don't trust them and it's just a car. I say my insurance can't handle another claim.", category: 'friends' },
  { title: "I ghosted a friend who only calls when they need something", body: "I realized my friend of 10 years only reaches out when they need a favor — money, rides, or emotional labor. I stopped responding. They're confused and hurt. I'm tired of a one-sided friendship but maybe I should have talked to them first.", category: 'friends' },
  { title: "I brought a plus-one to a friends-only dinner", body: "My friend organized a small dinner explicitly for our close friend group. I brought my new partner without asking. The host was visibly annoyed and the dynamic was off. I thought introducing my partner was natural.", category: 'friends' },
  { title: "I confronted my friend about copying my style", body: "My friend has been buying the same clothes, getting the same haircut, and copying my Instagram aesthetic. I told her it bothers me. She says imitation is flattery and I'm being narcissistic. I feel like I'm losing my identity.", category: 'friends' },
  { title: "I chose my partner over my best friend's birthday", body: "My partner surprised me with concert tickets for the same night as my best friend's 30th birthday party. I chose the concert. My friend says I've become one of those people who drops friends for a relationship.", category: 'friends' },
  { title: "I told my friend their kid was being a brat", body: "At a dinner party, my friend's child was throwing food, screaming, and hitting other kids. When my friend did nothing, I said 'Your kid is being a brat.' She grabbed her child and left. She says I had no right to comment on her parenting.", category: 'friends' },
  { title: "I started charging my friend for rides", body: "I've been driving my friend to work for a year — same commute route. Gas prices went up so I asked for $20/week. She was offended and said friends don't charge friends. I say $80/month in gas isn't nothing.", category: 'friends' },
  { title: "I didn't defend my friend in a group argument", body: "During a heated group discussion, everyone ganged up on my friend's opinion. I agreed with the group but stayed silent. My friend later said I should have stood up for them even if I disagreed. I say I shouldn't have to lie.", category: 'friends' },
  { title: "I regifted a present from my friend", body: "My friend gave me a necklace I didn't like. I regifted it to another friend. The original gifter saw the other friend wearing it at a party. She's deeply hurt. I didn't mean to be ungrateful — I just thought someone else would enjoy it more.", category: 'friends' },
  { title: "I posted a photo my friend asked me not to", body: "I took a great group photo at a party. My friend asked me not to post it because she thought she looked bad. I posted it anyway because I looked amazing in it. She's furious and says I violated her consent.", category: 'friends' },
  { title: "I matched with my friend's ex on a dating app", body: "I matched with my friend's ex on a dating app and went on a date without telling her. She found out through Instagram and feels betrayed. I say they broke up a year ago and she doesn't own dibs on people.", category: 'friends' },

  // MONEY (11)
  { title: "I asked my roommate to pay more rent", body: "My roommate and I split a 2-bedroom apartment 50/50. But their room is 40% larger and has an en-suite bathroom. I asked them to pay 60/40 instead. They say we agreed to 50/50 when we signed the lease and I'm changing the deal.", category: 'money' },
  { title: "I Venmo-requested a friend for a shared meal", body: "I paid for a group dinner ($200 for 5 people). I Venmo-requested everyone for their share. One friend is insulted, saying 'real friends don't keep tabs.' I say splitting costs fairly isn't keeping tabs — it's being an adult.", category: 'money' },
  { title: "I refused to tip 20%", body: "At a restaurant, the service was terrible — wrong orders, long waits, rude attitude. I left a 10% tip instead of the expected 20%. My dining companions were embarrassed and say servers depend on tips. I say tips should reflect service quality.", category: 'money' },
  { title: "I bought myself a luxury item while in debt", body: "I'm $15,000 in credit card debt but I bought a $1,200 designer bag because I found it at 70% off. My partner is furious, saying I'll never get out of debt with this mindset. I say the deal was too good to pass up and I deserved something nice.", category: 'money' },
  { title: "I didn't pay back a friend's 'gift'", body: "When I was struggling, my friend sent me $500 saying 'I've got you.' Now she's asking for it back, saying it was a loan. There was no written agreement and she used the word 'gift.' She says context made it clear it was temporary help.", category: 'money' },
  { title: "I haggled at a small business", body: "At a local artisan market, I asked a jewelry maker if she'd lower her price from $80 to $50. She was offended, saying handmade items aren't up for negotiation. I say negotiating is normal in markets. She says it's disrespectful to undervalue her work.", category: 'money' },
  { title: "I stopped paying for my friend's share", body: "In our friend group, I always end up paying for one friend who 'forgot their wallet' or 'will get me next time' but never does. I started ordering separately and declining to cover them. They say I'm being petty over small amounts.", category: 'money' },
  { title: "I charged my sibling rent to live with me", body: "My younger sibling moved in with me after losing their job. After 2 months, I started charging them modest rent ($400 for a room in my house). My parents say I shouldn't charge family. I say I have my own mortgage and bills.", category: 'money' },
  { title: "I kept a cashier's mistake in my favor", body: "A cashier accidentally gave me $20 extra in change. I noticed but didn't say anything. Later I felt guilty and my partner says I basically stole. I say the store makes enough profit and it was their error.", category: 'money' },
  { title: "I refused to donate to a friend's GoFundMe", body: "A friend set up a GoFundMe for an elective cosmetic surgery, framing it as a medical need. I didn't donate. She noticed and confronted me, saying I don't support her. I say GoFundMe isn't for optional procedures.", category: 'money' },
  { title: "I sold a gift someone gave me", body: "My aunt gave me an antique vase for my birthday. It's not my style and was collecting dust. I sold it online for $300. She found out and is heartbroken, saying it was a family heirloom. I didn't know its sentimental value.", category: 'money' },

  // ADDITIONAL MIXED (8)
  { title: "I faked a sick day for mental health", body: "I called in sick to work because I was emotionally burned out. I posted an Instagram story from a park, not thinking. My coworker saw it and told our boss. Now I'm facing a write-up. I say mental health is a valid reason to take a day off.", category: 'workplace' },
  { title: "I didn't tell a first date about my kids", body: "On a dating app, I didn't mention I have two kids. After three great dates, I told the truth. My date was shocked and said I wasted their time because they're not interested in parents. I say kids are a topic for when things get serious.", category: 'relationship' },
  { title: "I returned a worn dress to the store", body: "I bought an expensive dress, wore it to an event with the tags hidden, then returned it the next day. My friend saw me and called it 'retail fraud.' I say the return policy allows it and stores account for this.", category: 'money' },
  { title: "I told my neighbor they can't use my pool", body: "My neighbor's kids asked if they could swim in my pool during a heatwave. I said no because of liability concerns. They called me heartless. I say if someone gets hurt on my property, I'm legally responsible.", category: 'neighbors' },
  { title: "I gave away my friend's surprise party details", body: "I was helping plan a surprise party for our mutual friend. I accidentally mentioned the date while talking to the birthday person. The surprise was ruined. The party organizer says I can't be trusted. It was a genuine mistake.", category: 'friends' },
  { title: "I skipped my grandfather's funeral for a job interview", body: "My grandfather passed away the same week I had a crucial final-round job interview I'd been pursuing for months. I chose the interview. I got the job. My family says no job is worth missing a funeral. I say grandpa would have understood.", category: 'family' },
  { title: "I told a stranger their kid was misbehaving", body: "At a café, a kid was running around knocking into tables while the parent was on their phone. I politely asked the parent to manage their child. They exploded, saying I should mind my own business and I'm not their parent.", category: 'neighbors' },
  { title: "I unsubscribed my partner from their own streaming service", body: "My partner and I share streaming accounts. They subscribed to a 5th service we don't need. I cancelled it without telling them. When they noticed, they said I had no right to make financial decisions for them.", category: 'relationship' },
];

async function seed() {
  console.log('Seeding achievements...');
  for (const achievement of ACHIEVEMENTS_DATA) {
    await db.insert(achievements).values(achievement).onConflictDoNothing();
  }
  console.log(`Seeded ${ACHIEVEMENTS_DATA.length} achievements.`);

  console.log('Seeding scenarios...');
  const today = new Date();
  for (let i = 0; i < SCENARIOS_DATA.length; i++) {
    const publishDate = new Date(today);
    publishDate.setDate(today.getDate() + i);
    const dateStr = publishDate.toISOString().split('T')[0];

    await db.insert(scenarios).values({
      title: SCENARIOS_DATA[i].title,
      body: SCENARIOS_DATA[i].body,
      category: SCENARIOS_DATA[i].category,
      publishDate: dateStr,
      status: i === 0 ? 'published' : 'scheduled',
      source: 'editorial',
    }).onConflictDoNothing();
  }
  console.log(`Seeded ${SCENARIOS_DATA.length} scenarios (today + ${SCENARIOS_DATA.length - 1} days).`);

  console.log('Seed complete!');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
